CREATE DATABASE eSHOPPINGDB;
GO
USE eSHOPPINGDB;
GO

CREATE TABLE Customer (
    MaKH INT IDENTITY(1,1) PRIMARY KEY,
    HoTen NVARCHAR(100) NOT NULL,
    NgaySinh DATE NULL,
    CCCD_HoChieu NVARCHAR(30) NULL,
    DiaChi NVARCHAR(255) NULL,
    DienThoai NVARCHAR(20) NULL,
    Username NVARCHAR(50) NOT NULL UNIQUE,
    PasswordHash NVARCHAR(255) NOT NULL,
    Email NVARCHAR(100) NULL
);

CREATE TABLE Orders (
    MaDH INT IDENTITY(1,1) PRIMARY KEY,
    MaKH INT NOT NULL,
    NgayDat DATETIME NOT NULL DEFAULT GETDATE(),
    NguoiNhan NVARCHAR(100) NOT NULL,
    DiaChiNhan NVARCHAR(255) NOT NULL,
    DienThoaiNhan NVARCHAR(20) NOT NULL,
    TienHang DECIMAL(18,2) NOT NULL,
    PhiGiaoHang DECIMAL(18,2) NOT NULL,
    TongTien DECIMAL(18,2) NOT NULL,
    TrangThai NVARCHAR(50) NOT NULL,
    EmailXacNhan NVARCHAR(100) NULL,
    CONSTRAINT FK_Orders_Customer FOREIGN KEY (MaKH) REFERENCES Customer(MaKH)
);

CREATE TABLE OrderItem (
    MaDH INT NOT NULL,
    MaSP NVARCHAR(50) NOT NULL,
    TenSPSnapshot NVARCHAR(200) NOT NULL,
    DonGia DECIMAL(18,2) NOT NULL,
    SoLuong INT NOT NULL,
    PRIMARY KEY (MaDH, MaSP),
    CONSTRAINT FK_OrderItem_Order FOREIGN KEY (MaDH) REFERENCES Orders(MaDH)
);

CREATE TABLE Payment (
    MaThanhToan INT IDENTITY(1,1) PRIMARY KEY,
    MaDH INT NOT NULL,
    LoaiThe NVARCHAR(20) NOT NULL,
    MaskedCard NVARCHAR(30) NULL,
    PaymentReference NVARCHAR(100) NULL,
    SoTien DECIMAL(18,2) NOT NULL,
    TrangThai NVARCHAR(50) NOT NULL,
    ThoiGianThanhToan DATETIME NULL,
    CONSTRAINT FK_Payment_Order FOREIGN KEY (MaDH) REFERENCES Orders(MaDH)
);
GO
